version: '2.1'
services:
    mysql:
        build: ./db
        ports:
            - "3306:3306"
        healthcheck:
            test: "exit 0"

    api:
        build: .
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "8080:8080"
